import {
	app,
	BrowserWindow,
	screen,
	type BrowserWindowConstructorOptions as WindowOptions
} from 'electron'

// This import will automatically register all modules listeners
import './main/modules'

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
	app.quit()
}

export function createWindow(url: string, options: WindowOptions = {}) {
	const window = new BrowserWindow({
		width: 700,
		height: 473,
		...options
	})

	void window.loadURL(url)

	window.once('ready-to-show', () => {
		window.show()
	})

	if (process.env.NODE_ENV === 'development') window.webContents.openDevTools()

	return window
}

let mainWindow: BrowserWindow
export function createMainWindow() {
	const primaryDisplay = screen.getPrimaryDisplay()
	const { width, height } = primaryDisplay.workAreaSize

	mainWindow = createWindow(MAIN_WINDOW_WEBPACK_ENTRY, {
		width: width / 2,
		height: height / 2,
		webPreferences: {
			preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY
		}
	})
}

export function createChildWindow(url: string, options: WindowOptions = {}) {
	return createWindow(url, {
		...options,
		parent: mainWindow
		// modal: true
	})
}

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
	if (process.platform !== 'darwin') {
		app.quit()
	}
})

app.on('activate', () => {
	// On OS X it's common to re-create a window in the app when the
	// dock icon is clicked and there are no other windows open.
	if (BrowserWindow.getAllWindows().length === 0) {
		createMainWindow()
	}
})
