import path from 'path'
import os from 'os'
import {
	app,
	autoUpdater,
	BrowserWindow,
	screen,
	type BrowserWindowConstructorOptions as WindowOptions
} from 'electron'
import { API, type MainApi } from './modules/main_api'
import { handleDeepLink } from '@services/deep_links'
import { registerContextMenuListener } from './context_menus/main/context_menus_main'
import { registerDialogListeners } from './dialog/main/dialog_main'

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string

const platform = os.platform() + '_' + os.arch()
const version = app.getVersion()

autoUpdater.setFeedURL({
	url: 'https://taskly.fly.dev/desktop/update/' + platform + '/' + version
})

autoUpdater.checkForUpdates()

autoUpdater.on('update-downloaded', () => {
	autoUpdater.quitAndInstall()
})

autoUpdater.on('error', err => {
	console.error(err)
})

autoUpdater.on('checking-for-update', () => {
	console.log('Checking for update')
})

autoUpdater.on('update-available', () => {
	console.log('Update available')
})

autoUpdater.on('update-not-available', () => {
	console.log('Update not available')
})

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
	app.quit()
}

let mainWindow: BrowserWindow
let mainAPI: MainApi

if (process.defaultApp) {
	if (process.argv.length >= 2 && process.argv[1]) {
		app.setAsDefaultProtocolClient('taskly', process.execPath, [
			path.resolve(process.argv[1])
		])
	}
} else {
	app.setAsDefaultProtocolClient('taskly')
}

const gotTheLock = app.requestSingleInstanceLock()

if (!gotTheLock) {
	app.quit()
} else {
	app.on('second-instance', (event, commandLine) => {
		// Someone tried to run a second instance, we should focus our window.
		if (mainWindow) {
			if (mainWindow.isMinimized()) mainWindow.restore()
			mainWindow.focus()
		}

		const commandLineLastElement = commandLine.pop()
		if (commandLineLastElement) {
			handleDeepLink(commandLineLastElement.slice(0, -1), mainAPI)
		}
	})

	app.whenReady().then(() => {
		createMainWindow()
	})

	app.on('open-url', (event, url) => {
		handleDeepLink(url, mainAPI)
	})
}

export function createWindow(url: string, options: WindowOptions = {}) {
	const window = new BrowserWindow({
		width: 700,
		height: 473,
		...options
	})

	void window.loadURL(url)

	window.once('ready-to-show', () => {
		window.show()
	})

	if (process.env.NODE_ENV === 'development') window.webContents.openDevTools()

	return window
}

export function createMainWindow() {
	const primaryDisplay = screen.getPrimaryDisplay()
	const { width, height } = primaryDisplay.workAreaSize

	mainWindow = createWindow(MAIN_WINDOW_WEBPACK_ENTRY, {
		width: width / 2,
		height: height / 2,
		webPreferences: {
			preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
			nodeIntegration: true
		},
		transparent: true,
		titleBarStyle: 'hidden',
		vibrancy: 'fullscreen-ui',
		visualEffectState: 'active',
		backgroundMaterial: 'acrylic',
		titleBarOverlay: true,
		roundedCorners: true
	})

	initListenersAndWindowApi(mainWindow)
}

function initListenersAndWindowApi(window: BrowserWindow) {
	mainAPI = API(window)

	registerContextMenuListener()
	registerDialogListeners()

	void mainAPI.noteFileSystem.EnsureSystemFolders()
}

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
	if (process.platform !== 'darwin') {
		app.quit()
	}
})

app.on('activate', () => {
	// On OS X it's common to re-create a window in the app when the
	// dock icon is clicked and there are no other windows open.
	if (BrowserWindow.getAllWindows().length === 0) {
		createMainWindow()
	}
})
