export const STORE_KEY_DIRECTORY_HANDLE = 'STORE_KEY_DIRECTORY_HANDLE'
export const STORE_KEY_CACHED_FS_FILE = 'STORE_KEY_CACHED_FS_FILE'
export const STORE_KEY_CACHED_TREE = 'STORE_KEY_CACHED_TREE'
export const STORE_KEY_CACHED_NORMALIZED_FILES =
	'STORE_KEY_CACHED_NORMALIZED_TREE'
