name: (Mobile) Build Student Mobile App
run-name: ${{ inputs.platform }} -- ${{ inputs.channel }} -- ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        required: true
        description: Platform to build for
        options:
          - macos-latest
          - windows-latest
          - ubuntu-latest
      channel:
        type: choice
        required: true
        description: Build channel to use
        default: 'production'
        options:
          - beta
          - production
      version:
        type: choice
        required: true
        description: Version increment
        default: 'patch'
        options:
          - major
          - minor
          - patch

jobs:
  publish:
    runs-on: ${{ inputs.platform }}

    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
          cache: yarn

      - name: 🏗 Install deps (with cache)
        run: yarn install

      - name: ⬆️ Bump version
        run: yarn workspace @taskly/desktop version --${{ inputs.version }}

      - name: 🛠️ Publish
        run: CHANNEL=${{ inputs.channel }} yarn workspace @taskly/desktop publish

      - name: 📦 Update Release Notes
        uses: actions/github-script@v6
        with:
          script: |
            // Get all the commits since the last release
            // and update the release name with the channel
            const commits = await github.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: context.payload.repository.releases[0].tag_name,
              head: context.sha,
            });
            const releaseName = context.payload.repository.releases[0].name;
            const releaseNotes = commits.data.commits.map((commit) => {
              return `- ${commit.commit.message}`;
            });
            await github.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.repository.releases[0].id,
              name: `${releaseName}-${inputs.channel}`,
              body: releaseNotes.join('\n'),
            });
          github-token: ${{ secrets.GITHUB_TOKEN }}
